torchrun --nproc_per_node=8 --master_port=12345 train.py \
    --model_name_or_path EleutherAI/gpt-j-6b \
    --model_max_length 2048 \
    --data_path ./data/cnn_train.json \
    --dataloader_drop_last True \
    --bf16 True \
    --output_dir ./model \
    --num_train_epochs 3 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 2000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0.1 \
    --warmup_ratio 0.06 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap 'GPTJBlock' \
    --tf32 True \
